In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'

In [3]:
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [5]:
df = pd.read_csv(url)

/tmp/ipykernel_23472/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [4]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates
)

In [6]:
len(df)

1369765

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [9]:
!uv add sqlalchemy

Resolved 119 packages in 0.66ms
Audited 12 packages in 0.23ms

In [7]:
!uv add sqlalchemy psycopg2-binary

Resolved 120 packages in 0.70ms
Audited 13 packages in 0.26ms

In [8]:
!uv add sqlalchemy "psycopg[binary,pool]"

Resolved 120 packages in 0.70ms
Audited 13 packages in 0.25ms

In [9]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [10]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" FLOAT(53),
	tpep_pickup_datetime TEXT,
	tpep_dropoff_datetime TEXT,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	"RatecodeID" FLOAT(53),
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [33]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [10]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [14]:
df_iter = pd.read_csv(
   url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator = True,
    chunksize = 100000,
    
)

In [16]:
df = next(df_iter)

In [17]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
100000,2,2021-01-04 14:42:51,2021-01-04 14:51:18,1,1.43,1,N,170,161,2,7.5,0.0,0.5,0.00,0.0,0.3,10.80,2.5
100001,2,2021-01-04 14:04:39,2021-01-04 14:18:41,1,2.82,1,N,170,143,2,12.0,0.0,0.5,0.00,0.0,0.3,15.30,2.5
100002,1,2021-01-04 14:12:49,2021-01-04 14:31:21,0,2.70,1,N,68,239,1,13.5,2.5,0.5,3.35,0.0,0.3,20.15,2.5
100003,1,2021-01-04 14:43:55,2021-01-04 14:48:45,1,0.70,1,N,246,68,2,5.5,2.5,0.5,0.00,0.0,0.3,8.80,2.5
100004,1,2021-01-04 14:59:16,2021-01-04 15:07:08,1,1.60,1,N,161,234,1,8.0,2.5,0.5,2.25,0.0,0.3,13.55,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,2021-01-06 17:02:39,2021-01-06 17:09:21,2,1.10,1,N,236,237,1,6.5,3.5,0.5,3.20,0.0,0.3,14.00,2.5
199996,1,2021-01-06 17:12:00,2021-01-06 17:17:55,1,1.60,1,N,237,239,1,7.0,3.5,0.5,2.25,0.0,0.3,13.55,2.5
199997,2,2021-01-06 17:03:41,2021-01-06 17:07:37,2,1.06,1,N,161,186,1,5.5,1.0,0.5,1.96,0.0,0.3,11.76,2.5
199998,2,2021-01-06 17:14:11,2021-01-06 17:29:58,2,5.24,1,N,68,238,1,18.0,1.0,0.5,1.00,0.0,0.3,23.30,2.5
199999,2,2021-01-06 17:45:43,2021-01-06 17:52:37,2,1.49,1,N,68,114,1,7.0,1.0,0.5,1.50,0.0,0.3,12.80,2.5

In [11]:
!uv add tqdm

Resolved 120 packages in 0.71ms
Audited 13 packages in 0.26ms

In [12]:
from tqdm.auto import tqdm

In [15]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]